# Generated by Django 3.0.2 on 2020-06-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
