# Generated by Django 3.0.2 on 2020-06-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0009_auto_20200602_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_image/Profile/default.png', upload_to='user_image/Profile'),
        ),
    ]
